version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: library_postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - library_data:/var/lib/postgresql/data

volumes:
  library_data:
